await import("./tests/cli_init_test.ts")
await import("./tests/cli_sitemap_test.ts")
await import("./tests/cli_reindex_test.ts")
await import("./tests/cli_publish_test.ts")
await import("./tests/server_createsite_test.ts")
await import("./tests/server_emptysite_test.ts")